[package]
name = "mysqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.*"
heapless = "0.8.*"
clap = { version = "4.5.*", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
dirs = "6.0.0"
